/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.edu.bsi.view;

import br.ifpr.edu.bsi.bean.Livro;
import br.ifpr.edu.bsi.dao.LivroDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author aliss
 */
public class FormLivro extends javax.swing.JFrame {

    /**
     * Creates new form FormLivro
     */
    public FormLivro() {
        initComponents();
    }
    
    private Livro retornaObjeto(){
        Livro l = new Livro();
        l.setDescricaoLivro(jTFDescricao.getText().toUpperCase());
        l.setEdicaoLivro(Integer.parseInt(jTFEdicao.getText()));
        l.setAutorLivro(jTFAutor.getText().toUpperCase());
        l.setEditoraLivro(jTFEditora.getText().toUpperCase());
        l.setQuantidadeLivro(Integer.parseInt(jTFQuantidade.getText()));
        return l;
        
    }
    
    public void limparCampos(){
        jTFDescricao.setText("");
        jTFEdicao.setText("");
        jTFAutor.setText("");
        jTFEditora.setText("");
        jTFQuantidade.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBDescricao = new javax.swing.JLabel();
        jLBEdicao = new javax.swing.JLabel();
        jLBAutor = new javax.swing.JLabel();
        jLBEditora = new javax.swing.JLabel();
        jLBQuantidade = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jTFEditora = new javax.swing.JTextField();
        jTFAutor = new javax.swing.JTextField();
        jTFEdicao = new javax.swing.JTextField();
        jTFDescricao = new javax.swing.JTextField();
        jBTLimpar = new javax.swing.JButton();
        jBTSalvar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livro");

        jLBDescricao.setText("Descrição:");

        jLBEdicao.setText("Edição:");

        jLBAutor.setText("Autor:");

        jLBEditora.setText("Editora:");

        jLBQuantidade.setText("Quantidade:");

        jTFEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEdicaoActionPerformed(evt);
            }
        });

        jBTLimpar.setText("Limpar");
        jBTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTLimparActionPerformed(evt);
            }
        });

        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTCancelar.setText("Cancelar");
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBQuantidade)
                            .addComponent(jLBEditora)
                            .addComponent(jLBAutor)
                            .addComponent(jLBEdicao))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jTFQuantidade)
                            .addComponent(jTFDescricao)
                            .addComponent(jTFEdicao)
                            .addComponent(jTFAutor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jBTLimpar)
                        .addGap(32, 32, 32)
                        .addComponent(jBTSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(jBTCancelar)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBEdicao)
                    .addComponent(jTFEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBAutor)
                    .addComponent(jTFAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBEditora)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLBQuantidade)
                            .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTFEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTLimpar)
                    .addComponent(jBTSalvar)
                    .addComponent(jBTCancelar))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jBTLimparActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        try {
            LivroDao.inserir(retornaObjeto());
            //JOptionPane.showMessageDialog(null, "Dados salvos com sucesso", "Livro", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso", "Livro", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Salvo com sucesso");
        } catch (SQLException ex) {
            ex.printStackTrace();
            System.out.println("Não foi possível salvar");
        }
        
        limparCampos();
                       // TODO add your handling code here:
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
            this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jBTCancelarActionPerformed

    private void jTFEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEdicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivro().setVisible(true);
        }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTCancelar;
    private javax.swing.JButton jBTLimpar;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JLabel jLBAutor;
    private javax.swing.JLabel jLBDescricao;
    private javax.swing.JLabel jLBEdicao;
    private javax.swing.JLabel jLBEditora;
    private javax.swing.JLabel jLBQuantidade;
    private javax.swing.JTextField jTFAutor;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFEdicao;
    private javax.swing.JTextField jTFEditora;
    private javax.swing.JTextField jTFQuantidade;
    // End of variables declaration//GEN-END:variables
}
