/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.edu.bsi.view;

import br.ifpr.edu.bsi.bean.Familia;
import br.ifpr.edu.bsi.bean.Ordem;
import br.ifpr.edu.bsi.dao.FamiliaDao;
import br.ifpr.edu.bsi.dao.OrdemDao;
import br.ifpr.edu.bsi.util.Relatorio;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FormFamiliaPrincipal extends javax.swing.JFrame {
    private List<Familia> listaFamilia = new ArrayList<Familia>();
    
    private void atualizaTabela(){
          try 
            {
              listaFamilia = FamiliaDao.pesquisar(retornaObjeto());
          
          DefaultTableModel modelo = (DefaultTableModel) jTBFamilia.getModel();
         modelo.setNumRows(0);//criacao de um modelo para permitir alteração do banco na interface
         for (Familia familia : listaFamilia) {
             modelo.addRow(new Object[]{//adicionar familias presentes no banco
                familia.getNomeFamilia(),
                familia.getComprimentoFamilia(),
                familia.getAlimentaçãoFamilia(),
                familia.getOrdemFamilia().getNomeOrdem()
            });
        }
          } catch (SQLException ex) {
             System.out.println("Dados não disponíveis.");
         }
    }
    
    private Familia retornaObjeto() {
        Familia f = new Familia();
        f.setNomeFamilia(jTFFamilia.getText().toUpperCase());
        return f;
    }
    /**
     * Creates new form FormFamilia
     */
    public FormFamiliaPrincipal() {
        initComponents();
        atualizaTabela();
        jBTEditar.setEnabled(false);
        jBTExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBFamilia = new javax.swing.JTable();
        jTFFamilia = new javax.swing.JTextField();
        jLBFamilia = new javax.swing.JLabel();
        jBTNovo = new javax.swing.JButton();
        jBTImprimir = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jBTSair = new javax.swing.JButton();
        jBTRelatorioGeral = new javax.swing.JButton();
        jBTEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Família");

        jTBFamilia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTBFamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tamanho", "Alimentação", "Ordem"
            }
        ));
        jTBFamilia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBFamiliaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBFamilia);

        jTFFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFamiliaActionPerformed(evt);
            }
        });
        jTFFamilia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFFamiliaKeyPressed(evt);
            }
        });

        jLBFamilia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBFamilia.setText("Família: ");

        jBTNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/BotaoNovo.png"))); // NOI18N
        jBTNovo.setText("Novo");
        jBTNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNovoActionPerformed(evt);
            }
        });

        jBTImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/arrow_down.png"))); // NOI18N
        jBTImprimir.setText("Relatório");
        jBTImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTImprimirActionPerformed(evt);
            }
        });

        jBTExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        jBTSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jBTSair.setText("Sair");
        jBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSairActionPerformed(evt);
            }
        });

        jBTRelatorioGeral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTRelatorioGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/arrow_down.png"))); // NOI18N
        jBTRelatorioGeral.setText("Relatório Geral");
        jBTRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRelatorioGeralActionPerformed(evt);
            }
        });

        jBTEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/BotaoEditar.png"))); // NOI18N
        jBTEditar.setText("Editar");
        jBTEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBTNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTRelatorioGeral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTSair)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLBFamilia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFFamilia)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBTExcluir)
                        .addComponent(jBTSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBTNovo)
                        .addComponent(jBTImprimir)
                        .addComponent(jBTRelatorioGeral)
                        .addComponent(jBTEditar)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFamiliaActionPerformed

    private void jTFFamiliaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFamiliaKeyPressed
        atualizaTabela();
    }//GEN-LAST:event_jTFFamiliaKeyPressed

    private void jTBFamiliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBFamiliaMouseClicked
        jBTEditar.setEnabled(true);
        jBTExcluir.setEnabled(true);
    }//GEN-LAST:event_jTBFamiliaMouseClicked

    private void jBTNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNovoActionPerformed
        new FormFamilia().setVisible(true);
    }//GEN-LAST:event_jBTNovoActionPerformed

    private void jBTImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTImprimirActionPerformed
        try {
            Relatorio.gerarRelatorio("relatorios\\relatoriofamilianew.jasper", FamiliaDao.retornaRsFamilia(retornaObjeto()));
                    } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jBTImprimirActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        Familia familia = listaFamilia.get(jTBFamilia.getSelectedRow());
         
         int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir a família?");
         
         if(opcao == JOptionPane.YES_OPTION){
             try{
                 FamiliaDao.excluir(familia);
                 atualizaTabela();
             }catch (SQLException e){
                 e.printStackTrace();
         }
         }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    private void jBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBTSairActionPerformed

    private void jBTRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRelatorioGeralActionPerformed
        try {
            Relatorio.gerarRelatorio("relatorios\\RelatorioGeralFamilia.jasper", FamiliaDao.retornaRsGeral(retornaObjeto()));
                    } catch (SQLException ex) {
            Logger.getLogger(FormFamiliaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTRelatorioGeralActionPerformed

    private void jBTEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTEditarActionPerformed
        Familia familia = listaFamilia.get(jTBFamilia.getSelectedRow());
        new FormFamilia(familia).setVisible(true);
    }//GEN-LAST:event_jBTEditarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFamiliaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFamiliaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFamiliaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFamiliaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFamiliaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTEditar;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTImprimir;
    private javax.swing.JButton jBTNovo;
    private javax.swing.JButton jBTRelatorioGeral;
    private javax.swing.JButton jBTSair;
    private javax.swing.JLabel jLBFamilia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTBFamilia;
    private javax.swing.JTextField jTFFamilia;
    // End of variables declaration//GEN-END:variables
}
