/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.edu.bsi.view;

import br.ifpr.edu.bsi.bean.Classe;
import br.ifpr.edu.bsi.bean.Ordem;
import br.ifpr.edu.bsi.bean.Familia;
import br.ifpr.edu.bsi.dao.FamiliaDao;
//import br.ifpr.edu.bsi.dao.ClasseDao;
import br.ifpr.edu.bsi.dao.OrdemDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormFamilia extends javax.swing.JFrame {
    private List<Ordem> listaOrdem = new ArrayList<Ordem>();
    private boolean salvar;
    private int id;
    /**
     * Creates new form FormFamiliaPrincipal
     */
    public FormFamilia() {
        initComponents();
        preencherCombo();
        limparCampos();
        salvar = true;
    }
    
    public FormFamilia(Familia familia) {
        initComponents();
        jTFFamilia.setText(familia.getNomeFamilia());
        jTFComprimento.setText(familia.getComprimentoFamilia());
        jTFAlimentacao.setText(familia.getAlimentaçãoFamilia());
        preencherCombo();
        jCBOrdem.setSelectedItem(familia.getOrdemFamilia().getNomeOrdem());
        id = familia.getIdFamilia();
        salvar = false;
    }
    
    private void preencherCombo(){
        try{
            jCBOrdem.removeAllItems();
            jCBOrdem.addItem("Selecione uma Ordem");
            listaOrdem = OrdemDao.listar();
            
            for (Ordem ordem : listaOrdem){
                jCBOrdem.addItem(ordem.getNomeOrdem());
            }
        }catch (SQLException e){
            e.printStackTrace();
            System.out.println("Falha no carregamento da combo");
        }
        
    }
    private Familia retornaObjeto(){
        Familia familia = new Familia();
        familia.setNomeFamilia(jTFFamilia.getText().toUpperCase());
        familia.setComprimentoFamilia(jTFComprimento.getText().toUpperCase());
        familia.setAlimentaçãoFamilia(jTFAlimentacao.getText().toUpperCase());
        Ordem ordemSelecionada = listaOrdem.get(jCBOrdem.getSelectedIndex()-1); //recupera o dado selecionado pelo usuario no combo box
        familia.setOrdemFamilia(ordemSelecionada);
        familia.setIdFamilia(id);
        
        return familia;
    }
    
    private void limparCampos(){
        jTFFamilia.setText("");
        jTFComprimento.setText("");
        jTFAlimentacao.setText("");
        jCBOrdem.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFFamilia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLBAlimentacao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFComprimento = new javax.swing.JTextField();
        jTFAlimentacao = new javax.swing.JTextField();
        jCBOrdem = new javax.swing.JComboBox<>();
        jBTSalvar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Família");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tamanho:");

        jLBAlimentacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBAlimentacao.setText("Alimentação:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ordem:");

        jCBOrdem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBOrdem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordem" }));

        jBTSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/DisqueteSalvar.png"))); // NOI18N
        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jBTCancelar.setText("Cancelar");
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLBAlimentacao)
                            .addGap(18, 18, 18)
                            .addComponent(jTFAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFFamilia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBTSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBTCancelar)
                            .addGap(56, 56, 56)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49)
                        .addComponent(jCBOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBAlimentacao)
                    .addComponent(jTFAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTSalvar)
                    .addComponent(jBTCancelar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        try{
                if(salvar){
                FamiliaDao.inserir(retornaObjeto());
                System.out.println("Salvo com sucesso");
                JOptionPane.showMessageDialog(null, "Salvo com sucesso", "Salvar", JOptionPane.INFORMATION_MESSAGE);
                } else {
                FamiliaDao.alterar(retornaObjeto());
                System.out.println("Editado com sucesso");
                JOptionPane.showMessageDialog(null, "Editado com sucesso", "Editar", JOptionPane.INFORMATION_MESSAGE);
            }
            }catch (SQLException ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Selecione uma ordem", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            limparCampos();
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBTCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFamilia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTCancelar;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JComboBox<String> jCBOrdem;
    private javax.swing.JLabel jLBAlimentacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFAlimentacao;
    private javax.swing.JTextField jTFComprimento;
    private javax.swing.JTextField jTFFamilia;
    // End of variables declaration//GEN-END:variables
}
