/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.edu.bsi.view;

import br.ifpr.edu.bsi.bean.Classe;
import br.ifpr.edu.bsi.bean.Filo;
import br.ifpr.edu.bsi.bean.Ordem;
import br.ifpr.edu.bsi.dao.ClasseDao;
import br.ifpr.edu.bsi.dao.FiloDao;
import br.ifpr.edu.bsi.dao.OrdemDao;
import br.ifpr.edu.bsi.util.Relatorio;
import java.sql.SQLException;
//import java.sql.se
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FormClassePrincipal extends javax.swing.JFrame {
    private List<Classe> listaClasse = new ArrayList<Classe>();
    
    private void atualizaTabela(){
          try 
            {
              listaClasse = ClasseDao.pesquisar(retornaObjeto());
          
          DefaultTableModel modelo = (DefaultTableModel) jTBClasse.getModel();
         modelo.setNumRows(0);//criacao de um modelo para permitir alteração do banco na interface
         for (Classe classe: listaClasse) {
             modelo.addRow(new Object[]{//adicionar classes presentes no banco
                 classe.getNomeClasse(),
                 classe.getFiloClasse().getNomeFilo()
            });
        }
          } catch (SQLException ex) {
             System.out.println("Dados não disponíveis.");
         }
    }
    
    private Classe retornaObjeto() {
        Classe c = new Classe();
        c.setNomeClasse(jTFClasse.getText().toUpperCase());
        return c;
    }
    public FormClassePrincipal() {
        initComponents();
        atualizaTabela();
        jBTEditar.setEnabled(false);
        jBTExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBClasse = new javax.swing.JLabel();
        jBTNovo = new javax.swing.JButton();
        jBTImprimir = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jBTSair = new javax.swing.JButton();
        jTFClasse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBClasse = new javax.swing.JTable();
        jBTEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Classe");

        jLBClasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBClasse.setText("Classe:");

        jBTNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/BotaoNovo.png"))); // NOI18N
        jBTNovo.setText("Novo");
        jBTNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNovoActionPerformed(evt);
            }
        });

        jBTImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/arrow_down.png"))); // NOI18N
        jBTImprimir.setText("Imprimir");
        jBTImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTImprimirActionPerformed(evt);
            }
        });

        jBTExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        jBTSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jBTSair.setText("Sair");
        jBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSairActionPerformed(evt);
            }
        });

        jTFClasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFClasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFClasseKeyPressed(evt);
            }
        });

        jTBClasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTBClasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Filo"
            }
        ));
        jTBClasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBClasseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBClasse);

        jBTEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/BotaoEditar.png"))); // NOI18N
        jBTEditar.setText("Editar\n");
        jBTEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLBClasse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFClasse)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBTNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTSair)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBClasse)
                    .addComponent(jTFClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTExcluir)
                    .addComponent(jBTImprimir)
                    .addComponent(jBTNovo)
                    .addComponent(jBTSair)
                    .addComponent(jBTEditar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNovoActionPerformed
        new FormClasse().setVisible(true);
    }//GEN-LAST:event_jBTNovoActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        Classe classe = listaClasse.get(jTBClasse.getSelectedRow());
         
         int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir a ordem?");
         
         if(opcao == JOptionPane.YES_OPTION){
             try{
                 ClasseDao.excluir(classe);
                 atualizaTabela();
             }catch (SQLException e){
                 e.printStackTrace();
         }
         }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    private void jBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBTSairActionPerformed

    private void jTFClasseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFClasseKeyPressed
        atualizaTabela();
    }//GEN-LAST:event_jTFClasseKeyPressed

    private void jTBClasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBClasseMouseClicked
        jBTEditar.setEnabled(true);
        jBTExcluir.setEnabled(true);
    }//GEN-LAST:event_jTBClasseMouseClicked

    private void jBTImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTImprimirActionPerformed
        try {
            Relatorio.gerarRelatorio("relatorios\\relatorioclasse.jasper", ClasseDao.retornaRsClasse(retornaObjeto()));
                    } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBTImprimirActionPerformed

    private void jBTEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTEditarActionPerformed
        Classe classe = listaClasse.get(jTBClasse.getSelectedRow());
        new FormClasse(classe).setVisible(true);
    }//GEN-LAST:event_jBTEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClassePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClassePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClassePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClassePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClassePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTEditar;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTImprimir;
    private javax.swing.JButton jBTNovo;
    private javax.swing.JButton jBTSair;
    private javax.swing.JLabel jLBClasse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTBClasse;
    private javax.swing.JTextField jTFClasse;
    // End of variables declaration//GEN-END:variables
}
