/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.edu.bsi.view;

import br.ifpr.edu.bsi.bean.Filo;
import br.ifpr.edu.bsi.bean.Reino;
import br.ifpr.edu.bsi.dao.FiloDao;
import br.ifpr.edu.bsi.dao.ReinoDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
//import java.util.logging.Level;
//import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class FormFilo extends javax.swing.JFrame {
    private List<Reino> listaReino = new ArrayList<Reino>();
    private boolean salvar;
    private int id;
    
    /**
     * Creates new form FormFilo
     */
    public FormFilo() {
        initComponents();
        preencherCombo();
        salvar = true;
        limparCampos();
    }
    
    public FormFilo(Filo filo){
        initComponents();
        jTFFilo.setText(filo.getNomeFilo());
        preencherCombo();
        jCBReino.setSelectedItem(filo.getReinoFilo().getNomeReino());
        id = filo.getIdFilo();    
        salvar = false;
    }
    
     private void preencherCombo(){
        try{
            jCBReino.removeAllItems();
            jCBReino.addItem("Selecione um Reino");
            listaReino = ReinoDao.listar();
            
            for (Reino reino : listaReino){
                jCBReino.addItem(reino.getNomeReino());
            }
        }catch (SQLException e){
            e.printStackTrace();
            System.out.println("Falha no carregamento da combo");
        }
        
    }
    
    private Filo retornaObjeto(){
        Filo filo = new Filo ();
        filo.setNomeFilo(jTFFilo.getText().toUpperCase());
        Reino reinoSelecionado = listaReino.get(jCBReino.getSelectedIndex()-1); //recupera o dado selecionado pelo usuario no combo box
        filo.setReinoFilo(reinoSelecionado);
        filo.setIdFilo(id);
        
        return filo;
    }
    
    private void limparCampos(){
        jTFFilo.setText("");
        jCBReino.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLBReino = new javax.swing.JLabel();
        jTFFilo = new javax.swing.JTextField();
        jCBReino = new javax.swing.JComboBox<>();
        jBTSalvar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filo");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLBReino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBReino.setText("Reino:");

        jTFFilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFiloActionPerformed(evt);
            }
        });

        jCBReino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBReino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reino" }));

        jBTSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/DisqueteSalvar.png"))); // NOI18N
        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jBTCancelar.setText("Cancelar");
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLBReino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFFilo)
                    .addComponent(jCBReino, 0, 306, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTCancelar)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFFilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBReino)
                    .addComponent(jCBReino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTSalvar)
                    .addComponent(jBTCancelar))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFiloActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
         try {
             if(salvar){
                FiloDao.inserir(retornaObjeto());
                System.out.println("Salvo com sucesso");
                JOptionPane.showMessageDialog(null, "Salvo com sucesso", "salvo", JOptionPane.INFORMATION_MESSAGE);
             }else {
                 FiloDao.alterar(retornaObjeto());
                 System.out.println("Editado com sucesso");
                 JOptionPane.showMessageDialog(null, "Editado com sucesso", "Editar", JOptionPane.INFORMATION_MESSAGE);
             }
         } catch (SQLException ex) {
             ex.printStackTrace();
             JOptionPane.showMessageDialog(null, "Reino deve ser selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
         limparCampos();
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBTCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTCancelar;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JComboBox<String> jCBReino;
    private javax.swing.JLabel jLBReino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFFilo;
    // End of variables declaration//GEN-END:variables
}
