/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.edu.bsi.view;

import br.ifpr.edu.bsi.bean.Classe;
import br.ifpr.edu.bsi.bean.Filo;

import br.ifpr.edu.bsi.dao.ClasseDao;
import br.ifpr.edu.bsi.dao.FiloDao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormClasse extends javax.swing.JFrame {
    private List<Filo> listaFilo = new ArrayList<Filo>();
    private boolean salvar;
    private int id;
    
    public FormClasse() {
        initComponents();
        preencherCombo();
        salvar = true;
    }
    
    public FormClasse(Classe classe){
        initComponents();
        jTFClasse.setText(classe.getNomeClasse());
        preencherCombo();
        jCBFilo.setSelectedItem(classe.getFiloClasse().getNomeFilo());
        id = classe.getIdClasse();
        salvar = false;
        
    }
    
       private void preencherCombo(){
        try{
            jCBFilo.removeAllItems();
            jCBFilo.addItem("Selecione um Filo");
            listaFilo = FiloDao.listar();
            
            for (Filo filo : listaFilo){
                jCBFilo.addItem(filo.getNomeFilo());
            }
        }catch (SQLException e){
            e.printStackTrace();
            System.out.println("Falha no carregamento da combo");
        }
        
    }
    
    private  Classe retornaObjeto(){
        Classe classe = new Classe ();
        classe.setNomeClasse(jTFClasse.getText().toUpperCase());
        Filo filoSelecionado = listaFilo.get(jCBFilo.getSelectedIndex()-1); //recupera o dado selecionado pelo usuario no combo box
        classe.setFiloClasse(filoSelecionado);
        classe.setIdClasse(id);
        
        return classe;
    }
    
    private void limparCampos(){
        jTFClasse.setText("");
        jCBFilo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBNome = new javax.swing.JLabel();
        jLBFilo = new javax.swing.JLabel();
        jBTSalvar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();
        jTFClasse = new javax.swing.JTextField();
        jCBFilo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Classe");
        setResizable(false);

        jLBNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBNome.setText("Nome:");

        jLBFilo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBFilo.setText("Filo:");

        jBTSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/DisqueteSalvar.png"))); // NOI18N
        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jBTCancelar.setText("Cancelar");
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCancelarActionPerformed(evt);
            }
        });

        jCBFilo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBFilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filo" }));
        jCBFilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFiloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBNome)
                    .addComponent(jLBFilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFClasse)
                    .addComponent(jCBFilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jBTSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTCancelar)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBNome)
                    .addComponent(jTFClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBFilo)
                    .addComponent(jCBFilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTSalvar)
                    .addComponent(jBTCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCBFiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFiloActionPerformed
        
    }//GEN-LAST:event_jCBFiloActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        try {
            if(salvar){
                ClasseDao.inserir(retornaObjeto());
                System.out.println("Salvo com sucesso");
                JOptionPane.showMessageDialog(null, "Salvo com sucesso", "Salvar", JOptionPane.INFORMATION_MESSAGE);
            }else {
                ClasseDao.alterar(retornaObjeto());
                System.out.println("Editado com sucesso");
                JOptionPane.showMessageDialog(null, "Editado com sucesso", "Edição", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        limparCampos();
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBTCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClasse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTCancelar;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JComboBox<String> jCBFilo;
    private javax.swing.JLabel jLBFilo;
    private javax.swing.JLabel jLBNome;
    private javax.swing.JTextField jTFClasse;
    // End of variables declaration//GEN-END:variables
}
